name: Mirror

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-FUN-400-BDX-4-1-wolfram-nolann.dubos.git"
  EXECUTABLES: "nanotekspice"

jobs:
  push_to_mirror:
    name: Push to Mirror Repository
    if: github.repository != 'EpitechPromo2028/B-FUN-400-BDX-4-1-wolfram-nolann.dubos.git'
    runs-on: ubuntu-latest
    container: 
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          target_repo_url: ${{ env.MIRROR_URL }}
